### ISSUE TITLE
Build Sponsor Us page

### ISSUE THREAD

**Issue by egiurleo** [wnbrb/wnb-rb-site#10]
For design, check out our [Figma document](https://www.figma.com/file/KXxpiCLvLRvPtRy1L4fTfq/WNB.rb?node-id=96%3A990).

This page should be at the url `/sponsor-us`.

It should not pull any information from the backend and be completely hard-coded in the frontend.

Each of the "Become a ___ Sponsor" links should be a mailto link to the address `womennonbinary.rb@gmail.com` and the subject line `Becoming a ___ Sponsor` (where the sponsorship type is filled in).

Please let me know if you need access to Figma to download SVGs!

**Comment by EvaKrizal** [comment]
Hi, is this issue available?

**Comment by egiurleo** [comment]
Hi, @EvaKrizal! No this issue is taken. If you're looking for React work, issue #4 is still open!

**Comment by egiurleo** [comment]
Closed by #41.
