### ISSUE TITLE
Add links to Speaker model / Meetup page

### ISSUE THREAD

**Issue by egiurleo** [wnbrb/wnb-rb-site#124]
We should send traffic to our incredible meetup speakers via links to their Twitter, GitHub, LinkedIn, and personal websites!

- [x] Add a column/columns to our `speakers` table where we can store links to their Twitter, GitHub, LinkedIn, and personal website.
  - I'm open to more types of links as well
  - Maybe we could make this a `jsonb` column for flexibility?
- [ ] Modify the meetup page to display these links for each speaker if they are available.

**Comment by RabeaGleissner** [comment]
I'm interested in working on this one!

**Comment by egiurleo** [comment]
@RabeaGleissner Assigned!

**Comment by RabeaGleissner** [comment]
I'll raise a PR for adding the `jsonb` column first.

For the UI I suggest adding each speaker link with the corresponding icon underneath the speaker description. Something like this (there would be more icons if people have more links):

![image](https://user-images.githubusercontent.com/8995723/206417588-8ebc401e-4ad7-4f62-b6b2-b16e300fa89c.png)

What do you think? Feedback is welcome!

Also - which icon to use for a personal website?

**Comment by luciagirasoles** [comment]
@egiurleo this ticket has a PR merged; could you please indicate whether there is anything missing?

**Comment by RabeaGleissner** [comment]
Hi @luciagirasoles ! Thanks for checking in on this! I haven't actually created the frontend part yet... apologies for the delay! Will do that this week.

**Comment by luciagirasoles** [comment]
Hi @RabeaGleissner it's ok. Please let us know if you require any further information or have any new suggestions to the project. We are continuously looking for ways to improve.

**Comment by RabeaGleissner** [comment]
Hi @luciagirasoles 
Thank you! And I did ask for feedback in one of my previous comments on the ticket. So if you have any opinions, let me know! If you don’t feel strongly about it, don’t worry. Happy to go with my suggestion. We can always change it!

https://github.com/wnbrb/wnb-rb-site/issues/124#issuecomment-1342590446

**Comment by luciagirasoles** [comment]
I like the idea about adding the icons. For the personal site I think we can use the [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Apublic%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4048)

**Comment by luciagirasoles** [comment]
Assigning @Huclaire
