### ISSUE TITLE
Fix alignment on past meetups page

### ISSUE THREAD

**Issue by egiurleo** [wnbrb/wnb-rb-site#130]
The gray bar on the past meetups page should be completely aligned all the way down the page, but some parts of it are aligned differently.

See it live: https://www.wnb-rb.dev/meetups

<img width="1440" alt="Screen Shot 2022-06-21 at 9 26 53 PM" src="https://user-images.githubusercontent.com/9601737/174923713-1051f4d7-a716-4d52-b2a4-f28db85faee7.png">

**Comment by RabeaGleissner** [comment]
Hello! I think I have a fix for this one 😃 
Will raise PR.
