### ISSUE TITLE
Set up website deployment pipeline

### ISSUE THREAD

**Issue by egiurleo** [wnbrb/wnb-rb-site#14]
This ticket involves a few steps:
- [x] Decide where to deploy (Heroku?)
- [x] Set up the initial deployment
- [x] Create a GitHub action that continuously deploys the website every time it is merged

I am happy to pair on this!

**Comment by EsterKais** [comment]
This guide seems to be a nice one to follow: https://medium.com/@michaelekpang/creating-a-ci-cd-pipeline-using-github-actions-b65bb248edfe
