### ISSUE TITLE
Job Board Apply Button is covering salary

### ISSUE THREAD

**Issue by angelamchoi** [wnbrb/wnb-rb-site#151]
**Describe the bug**
On the job board page, the first job's salary is covered by the Apply button. 

**Screenshots**
Desktop (Chrome and Firefox)
<img width="761" alt="Screenshot 2023-01-19 at 11 33 34 AM" src="https://user-images.githubusercontent.com/15877132/213503772-77fa9e8f-01c7-4715-8fad-56da69344cfa.png">

Mobile
<img width="431" alt="Screenshot 2023-01-19 at 11 35 41 AM" src="https://user-images.githubusercontent.com/15877132/213503816-23fa3d80-a9ab-4fb4-b200-24704e036b7f.png">

Safari
<img width="355" alt="Screenshot 2023-01-19 at 11 44 45 AM" src="https://user-images.githubusercontent.com/15877132/213504401-d470d26b-5203-4f84-b0ff-3f089c57fef0.png">

**Browser issue**
This issue is happening in Chrome and Firefox browsers. There is no issue in Safari. 

**Questions**
- Is this an issue I could work on?
- Do you know if this issue has occurred before?

**Comment by luciagirasoles** [comment]
job board has been closed for the moment
