### ISSUE TITLE
Broken link in the README.md file

### ISSUE THREAD

**Issue by Samgalgo** [wnbrb/wnb-rb-site#165]
I noticed there is a broken link in the README.md :)

- README.me:
   - Contributor Resources:
       - GitHub:
           - Creating and deleting branches ----- **link is broken**

<img width="814" alt="Screenshot 2023-03-28 at 9 21 01 PM" src="https://user-images.githubusercontent.com/82852120/228402032-1f62ffeb-ec64-4fd5-ae8b-463ff5d11a8f.png">

**Comment by luciagirasoles** [comment]
Hi @Samgalgo thank you for your feedback!🙇🏽‍♀️ .Can you help us fixing this?

**Comment by Samgalgo** [comment]
Hi @luciagirasoles yes I would love to work on this issue. I will be going through a change of computers. Is it ok if I take care of this at the mid of July? but if it needs to be fixed sooner and someone else wants to take on it I also understand :)

**Comment by luciagirasoles** [comment]
> Hi @luciagirasoles yes I would love to work on this issue. I will be going through a change of computers. Is it ok if I take care of this at the mid of July? but if it needs to be fixed sooner and someone else wants to take on it I also understand :)

It's ok. Let's see what happens first.

**Comment by jrussell416** [comment]
My pull request for this issue was approved, Can this be marked as closed if there's nothing else left for me to do
