### ISSUE TITLE
Run ESLint and Prettier on SCSS files during pre-commit hook

### ISSUE THREAD

**Issue by egiurleo** [wnbrb/wnb-rb-site#17]
Currently, we have ESLint and Prettier running on js and css files during pre-commit, but we recently started using scss files. I would like ESLint and Prettier to run on those files as well so they're properly formatted and free from issues!

**Comment by egiurleo** [comment]
@mairagee524 Yes absolutely!

**Comment by egiurleo** [comment]
Hi, @mairagee524! Are you still planning to work on this?

**Comment by egiurleo** [comment]
Hi @mairagee524, I'm going to unassign you from this issue for now. If you're still interested in working on it, please let me know and I'll re-assign you.

**Comment by Yogeshp0012** [comment]
Is this open to work ? If yes please assign it to me.

**Comment by Yogeshp0012** [comment]
Hi @egiurleo and @luciagirasoles, you have commented that eslint and prettier run on css and js files. But I can see the precommit hook to be only on "*.{js,jsx,json,md,html}" for prettier and "*.{js,jsx,ts,tsx}" for eslint. I do not see any CSS files added here. Should I include both CSS and SCSS?

**Comment by luciagirasoles** [comment]
Hi @Yogeshp0012 We had `.css` files instead of the current `.scss` files by the time this issue was created. It would be useful to include both.
