### ISSUE TITLE
Enhance the Meetups Section of the Site

### ISSUE THREAD

**Issue by adrianna-chang-shopify** [wnbrb/wnb-rb-site#190]
**Is your feature request related to a problem? Please describe.**
The website displays past meetups, but there isn't a lot of information about how our meetups actually work (Virtual / last Tues of every month / how to get an invite, etc.)

It would be great to have extra info on there about how our meetups work, as well as info for prospective speakers.

**Describe the solution you'd like**

I'm proposing we rename the "Past Meetups" section to a more general "Meetups" section, with a card describing how our meetups work. It would be great to include information for potential speakers as well, and if we could link to the meetup speaker form (https://docs.google.com/forms/d/e/1FAIpQLSdmOJxLdSdy74mXYxsr6ZRRhTN95Yxnq2B6n5mhUoGkVmDUGA/viewform) that would make it easier for folks interested in speaking to fill it in.

**Describe alternatives you've considered**

A future nice-to-have might be to integrate the speaker form right into the website, rather than using a Google Form, but this is simpler and a quick win in the short term!

**Additional context**

**Comment by luciagirasoles** [comment]
@adrianna-chang-shopify can you explain more about "the card describing how our meetups work"

**Comment by adrianna-chang-shopify** [comment]
Yes! I was thinking information along the lines of:
- When our meetups are
- What kind of talks there are
- Who can attend
- An invitation for speakers

I drafted up a blurb, feel free to include it / edit it / etc.:

---

WNB.rb meetups are held virtually on the last Tuesday of every month at 12pm Eastern Time. The content is typically Ruby or career-related, with 1-2 talks given in a lecture style format. Anyone who identifies as a woman or non-binary individual is welcome to attend. Fill in the form at <link to form to join WNB.rb> to get an invite to the Google Group, which will opt you into calendar invites for upcoming meetups.

Interested in speaking? We're always on the lookout for speakers, whether you're a seasoned vet or have never spoken before! Giving a talk at an WNB.rb meetup is a great way to sharpen your public speaking skills. Fill in <this form> with details if you're interested, or reach out to `@Adrianna Chang` on the WNB.rb Slack.
