### ISSUE TITLE
Donate page is down

### ISSUE THREAD

**Issue by liesas** [wnbrb/wnb-rb-site#201]
**Describe the bug**
When going to the donate page, I get greeted by this  
![Screenshot 2023-10-31 at 14 36 53](https://github.com/wnbrb/wnb-rb-site/assets/59622084/2d77a64b-38c2-4520-ad47-8715052c27e4)

**To Reproduce**
Go to https://www.wnb-rb.dev/donate

**Desktop (please complete the following information):**
 - OS: macOS 14.0
 - Browser: Chrome, Firefox
 - Version 118

**Comment by luciagirasoles** [comment]
Thank you for pointing it out
