### ISSUE TITLE
Admin: delete meetup

### ISSUE THREAD

**Issue by egiurleo** [wnbrb/wnb-rb-site#25]
## User story
As an admin user, I would like to delete an existing event.

## Notes
This ticket requires multiple steps:
- [ ] Creating a Admin::EventsController#delete controller action that edits an event with the provided id
  - [ ] This action should validate that there is a current_user and redirect to admin/login if no user is logged in.
  - [ ] If the meetup with the provided ID does not exist, the controller should redirect to the 404 page.
  - [ ] The action should redirect to the `admin/events` index page once the delete is complete with a banner saying "Event successfully deleted."
- [ ] Updating the `admin/events/index` and `admin/events/get` views to add a delete button

**Comment by aespringfield** [comment]
PR: https://github.com/wnbrb/wnb-rb-site/pull/104
