### ISSUE TITLE
Add Google Analytics to website

### ISSUE THREAD

**Issue by egiurleo** [wnbrb/wnb-rb-site#48]
It would be good for us to know information about how people are interacting with our website. To this end, we'd like to implement Google Analytics to keep tabs on how many people are visiting our site and what pages they're looking at.

In order to use Google Analytics, we must get the user's consent to use cookies. This will require us to create some sort of banner or overlay asking for consent. It can say something like:
> This website uses cookies to ensure you get the best experience. [Okay] [Decline]

If a user consents, then we can write some anonymized data to Google Analytics:
- [ ] Page visits
- [ ] Button clicks

I'm happy to pair on this with someone in order to give them access to the WNB.rb Google Analytics account.

**Comment by Yogeshp0012** [comment]
Hey @egiurleo , I would like to pair up. But idk much about google Analytics integration. Is it fine?
