### ISSUE TITLE
Add a custom 404 page

### ISSUE THREAD

**Issue by egiurleo** [wnbrb/wnb-rb-site#66]
Suggested by @sawiggins 

Our site doesn't currently have a custom 404 page! I'm happy to provide a design if necessary, but someone should feel free to come up with something. The page can be simple, but should still match the styles on the other pages of our site.

**Comment by S0han** [comment]
I would like to assist.
Please provide me with any relevant information.

**Comment by egiurleo** [comment]
Hi, @S0han! You can find instructions to set up the repo in the README. You can find the website design [here](https://www.figma.com/file/KXxpiCLvLRvPtRy1L4fTfq/WNB.rb?node-id=96%3A990) to get a sense of what the rest of the site looks like.

**Comment by DeannaMarbeck** [comment]
Hi @egiurleo, I'd like to have a go at this one please?

**Comment by egiurleo** [comment]
@DeannaMarbeck Yes! Assigning you now.

**Comment by luciagirasoles** [comment]
Hi @DeannaMarbeck. Is there any way we might assist you with this requirement? You've been assigned to this ticket for quite some time; please have a look at it soon or let me know so that I may un-assign you. If you ever want to try working on it again in the future, I’m happy to re-assign you, I just want to make room for other people to work on it if they want to.

**Comment by DeannaMarbeck** [comment]
Hi @luciagirasoles, thank you for the chase.  I have unassigned myself for the meantime so that someone else can pick it up if they wish.  Happy to jump back in the future when I have a bit of spare time.

**Comment by susott** [comment]
Hi, could I look into this?

**Comment by susott** [comment]
Hi, sorry, I don't find the time right now to do this.

**Comment by MooseCowBear** [comment]
I could work on this.

**Comment by luciagirasoles** [comment]
I've assigned you @MooseCowBear
