### ISSUE TITLE
Build past meetup page

### ISSUE THREAD

**Issue by egiurleo** [wnbrb/wnb-rb-site#7]
See designs on our [Figma](https://www.figma.com/file/KXxpiCLvLRvPtRy1L4fTfq/WNB.rb?node-id=96%3A990).

This ticket is currently blocked by the backend work of creating data models for our meetups.

The URL of this page should be `/meetups/<year>/<month>`.

- [ ] This page must work for both past panels and past meetups. 
- [ ] It should have one or more videos from the event, along with a title, description, and speaker info.
- [ ] The speaker bios can be put at a section on the bottom.
- [ ] This page should be linked from the cards on the `/meetups` page
- [ ] The `/meetups` page should be added back to the header and footer as "Past Meetups"

**Comment by DeannaMarbeck** [comment]
I would like to have a go at this @egiurleo if that's ok?

**Comment by egiurleo** [comment]
@DeannaMarbeck Yes absolutely!

**Comment by egiurleo** [comment]
Hey @DeannaMarbeck just a heads up that I added a couple more tasks for this ticket -- I'd like the links on the `/meetups` page to link to this page, and I'd like "Past Meetups" to be added back to the header and footer (I removed them in #81 because the links didn't exist yet).

**Comment by egiurleo** [comment]
Closed with #84
