### ISSUE TITLE
Add link to Remote Ruby in podcast section

### ISSUE THREAD

**Issue by egiurleo** [wnbrb/wnb-rb-site#73]
Jemma and I were recently on the [Remote Ruby podcast](https://remoteruby.com/162). It would be awesome if we added a link to this episode in the podcast section. This might require a bit of a redesign to include both podcast links.

**Comment by sawiggins** [comment]
Sorry, I should have probably commented here first. I worked on this issue this evening and opened a PR for it. ☺️
