### ISSUE TITLE
Add search to job board page

### ISSUE THREAD

**Issue by egiurleo** [wnbrb/wnb-rb-site#91]
Currently, our job board page does not allow a user to search through the jobs -- they must look through every single job manually. Search would make it easier for our community members to find jobs that are relevant to them!

## Possible approach:

One possible approach is just to provide one search box and allow the user to type anything in there (e.g. "Shopify" or "Senior Engineer") and then search ALL the fields on the jobs. This UI would be simpler, but the backend might be slightly harder to implement.

I'm not committed to this approach and am open to other suggestions!

## Success criteria

- [ ] Add a query param to the backend that searches for jobs that contain the provided string in one of their fields (title, company, location, description?). `query` is a potential name for this param.
- [ ] Remember to add any relevant indexes to make sure this functionality does not do a full table scan.
- [ ] Add the search UI to the job board frontend, and have it pass the search query to the backend when fetching jobs

**Comment by luciagirasoles** [comment]
job board has been closed for the moment
