### ISSUE TITLE
Allow visitor to donate an amount of their choosing

### ISSUE THREAD

**Issue by egiurleo** [wnbrb/wnb-rb-site#92]
Currently, users who visit our donate page can only donate pre-determined amounts. These amounts are stored in an array that contains a bunch of links to Stripe checkout pages.

I believe to accomplish this, we'll have to do the following (here's the [Stripe sessions API documentation](https://stripe.com/docs/api/checkout/sessions/object)):
- [ ] Add the `stripe` Ruby gem to the project
- [ ] when creating a session, in `line_items` -> `data` -> `price`, specify the `product` as our donation product ID, then specify the `price` as the value passed in by the user. This should generate a checkout URL that we can redirect the user to.
- [ ] Create a backend endpoint that encompasses this behavior and takes the price as a parameter.
- [ ] On the frontend, change one of the donation prices to "Other" and allow the user to specify an amount. Then, when they click the donate button, redirect them to the link returned by the backend.

Happy to pair with someone on this because it's a bit complicated!

**Comment by bhumi1102** [comment]
@egiurleo oo stripe stuff! Happy to pair on this or work on figuring it out..

**Comment by egiurleo** [comment]
@bhumi1102 Yeah that looks right! If you feel comfortable getting it to a place where all we need is the Stripe info, we can get on a call so I can share the Stripe creds and make sure everything is working! Let me know how that sounds.

**Comment by bhumi1102** [comment]
Yup feel comfortable implementing this, matter of squeezing it in spare time! First step, getting the site running locally, about to do that.

**Comment by egiurleo** [comment]
@bhumi1102 there is absolutely no rush - I'd rather you take your time and learn at a comfortable pace then rush to get it done. 💖

**Comment by luciagirasoles** [comment]
Hi @bhumi1102. Is there any way we might assist you with this requirement? You've been assigned to this ticket for quite some time; please have a look at it soon or let me know so that I may un-assign you. If you ever want to try working on it again in the future, I’m happy to re-assign you, I just want to make room for other people to work on it if they want to.

**Comment by bhumi1102** [comment]
All yours @luciagirasoles

**Comment by MooseCowBear** [comment]
I'd like to try setting this up. I have a couple questions though.

1. Where would I find the donation product ID?

2. Currently, the donate button opens the stripe checkout page in a new tab. In the stripe docs, it looks like this would change to redirecting to the stripe checkout page and then redirecting back to wnb after the checkout is complete. If that's correct, where should the redirect after checkout go? Maybe it would make sense to have a thank you page or something that acknowledged the successful donation?

**Comment by luciagirasoles** [comment]
First. @MooseCowBear Thank you for helping us with this Issue! I've assigned it to you.
> I'd like to try setting this up. I have a couple questions though.
> 
> 1. Where would I find the donation product ID?
> 2. Currently, the donate button opens the stripe checkout page in a new tab. In the stripe docs, it looks like this would change to redirecting to the stripe checkout page and then redirecting back to wnb after the checkout is complete. If that's correct, where should the redirect after checkout go? Maybe it would make sense to have a thank you page or something that acknowledged the successful donation?

1. Currently we manage  [payment method links](https://stripe.com/docs/payment-links) for each amount in the `datasource/index.js` file. Do you need something extra to set the custom value? I would recommend creating your account in Stripe and try to set this for as if you were the business. If you want extra help, don't hesitate to reach us and we will gladly answer any questions you may have.
2. We can start with the default way and then add the "thank you" page as a new issue. (divide➗ and conquer ➡️ 🌐💪🏽)

**Comment by MooseCowBear** [comment]
Hi @luciagirasoles, I forgot to ask which amount I should replace with the new "other" button. Is there an amount that is less chosen than the others?

**Comment by luciagirasoles** [comment]
@MooseCowBear It should be something like an input that allows only numbers like https://donate.wikimedia.org/
